### ISSUE TITLE
Incompatible with Java 8

### ISSUE THREAD

**Issue by vinithpillai** [grails-plugins/grails-webflow-plugin#9]
We are facing an issue with WebFlow when working under Java 8. It works fine with Java 7. We get the stacktrace as given below (given that all the inputs are the same from the screen):

org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.codehaus.groovy.grails.webflow.engine.builder.ClosureInvokingAction@1f11a4e5 in state '_EDITED_' of flow '_EDITED_' -- action execution attributes were 'map[[empty]]'
at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:189)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)

We tried this with JDK 1.8.0_60 and Grails 2.5.1

**Comment by jminiko** [comment]
any news for this blocking defect?

**Comment by vikasbo** [comment]
Any suggestions on how this could be avoided/overcome?

**Comment by vinithpillai** [comment]
> Any suggestions on how this could be avoided/overcome?

Well, we invested in spending a lot of hours to remove the webflow plugin. After the removal, our application was Java 8 compliant. Upgrading to Grails 3 and 4 is also worth the investment.
